// <auto-generated />
namespace Lind.DDD.Manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20200524 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200524));
        
        string IMigrationMetadata.Id
        {
            get { return "202005240456196_20200524"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
